on:
  push:
    branches:
      - main
name: Deploy
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
      
    - name: Build Project
      run: |
        npm install
        npm run build
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: 198.54.126.157
        username: drewh@drewh.net
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: public_html/asl
        local-dir: ./public/